name: <PLACEHOLDER>
description: Consists of resuable snippets from other issue templates to easily create new issue templates
title: "[<PLACEHOLDER>] kebap-cased-issue-name"
labels: ["Status: Pending", "Type: <PLACEHOLDER>"]
assignees:
  - username
body:
  - type: markdown
    attributes:
      value: |
        ### How to use this issue form
        
        Do **not** abuse a *<PLACEHOLDER>* to report *security vulnerabilities*.<br/>
        In such instances, act as described in the project's *security policy* or if the project does not specify how to report these incidents, open a *security advisory*.

        <details>
          <summary><ins><b>
            Click here for: What not to do when creating a <PLACEHOLDER> request
          </b></ins></summary>
          
          Do **not abuse** a *<PLACEHOLDER>* issue to test out new stuff that may or may not be included in the project, like, experimenting with new tools to see whether you can get them to work or whether they are appropriate for the project.
          Use a *feature request* or a *feature change request* instead, work on them on their own branch, and (if fitting) mark them with the `Flag: Suggestion` label.
          Keep in mind not all *opened* and *accepted* issues have to be resolved. They can also be *abandoned* if the experiments turn out as failure.

          Do **not** abuse a *<PLACEHOLDER>* issue to refactor the code itself, like renaming a variable or class.
          Do **not** abuse a *<PLACEHOLDER>* issue to fix a bug caused by, for example, a typo, and use a *bug report* instead.
          Use it **only** for <PLACEHOLDER>.
        
        </details>

        <details>
          <summary><ins><b>
            Click here for: How to handle multiple little <PLACEHOLDER> improvement suggestions in a single issue
          </b></ins></summary>
          
          If there are *multiple little improvement suggestions*, you can mention them bundled within a *single issue* because the effort of writing issues should not drastically surpass the effort of resolving them.<br/>
          Make sure to present each improvement **distinctly** from the rest and to use the **same order** of refinements in each section when bundling multiple improvements inside one issue.
          However, create a **separate** issue for each issue that is concerned with the *<PLACEHOLDER>* itself.
        
        </details>
        
        All text areas support markdown syntax unless explicitly noted otherwise.

        <details>
          <summary><ins><b>
            Click here for: Information for contributors about label usage
          </b></ins></summary>
          
          - select *any number* of fitting labels that have a `Flag: ` prefix
          - select *any number* of fitting labels that have a `For: ` prefix
          - select **exactly one** label that has a `Priority: ` prefix
          - select **exactly one** label that has a `Scope: ` prefix
          - **never** tamper with the initial `Status: Pending` label when creating an issue
          - **never** add, remove, or change any associations (or the lack thereof) between an issue and label that has a `Type: ` prefix
        
          Look at the label descriptions to grasp their proper usage and pick the most fitting.
          If more than one `Type: ` label fits the issue, it is a good indicator that the issue mixes concerns.
          You should then split this issue into multiple issues so that each new issue falls **exactly into one** category.
        
        </details>
        
        ---
  - type: input
    id: affected-version
    attributes:
      label: Affected Version
      description: Name the known versions or main branches of the project that the <PLACEHOLDER> affects.
      placeholder: e.g. Project Version 1.2.1, Project Version 2.0.0
    validations:
      required: true
  - type: input
    id: system-information
    attributes:
      label: System Information
      description: Name any potentially helpful information about the system(s) where the <PLACEHOLDER> appeared, like the operating system and its version, the browser and its version, device information, etc.
      placeholder: e.g. Windows 10 Pro 21H2 64-bit, Firefox 108.0.2 64-bit
    validations:
        required: true
  - type: textarea
    id: object-of-interest
    attributes:
      label: Object of Interest
      description: Describe the <PLACEHOLDER> parts that require overwork as specifical as possible.
      placeholder: <EXEMPLIFYING QUESTIONS>
    validations:
      required: true
  - type: textarea
    id: problem-motivation
    attributes:
      label: Problem/Motivation
      description: Describe your problem or motivation that caused your <PLACEHOLDER> request as detailed as possible.
      placeholder: <EXEMPLIFYING QUESTIONS>
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Describe why the mentioned parts require <PLACEHOLDER> as detailed as possible.
      placeholder: <EXEMPLIFYING QUESTIONS>
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe how you expected the program to behave as specifical as possible.
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Describe how to reproduce the <PLACEHOLDER> step-by-step as detailed as possible. Use an ordered list for this.
      placeholder: |
        1. I started here.
        2. Then, I did this.
        ...
    validations:
      required: true
  - type: textarea
    id: solution-proposal
    attributes:
      label: Solution Proposal
      description: Describe the solution that you have in mind as detailed as possible.
      placeholder: <EXEMPLIFYING QUESTIONS>
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe potential side effects of your solution proposal, which could cause follow-up issues (in particular <PLACEHOLDER> requests), to the best of your knowledge.
      placeholder: Could my solution proposal cause other problems?
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Write your question in full length as detailed as possible. Describe the object of confusion as specifical as possible. Also, describe possible subquestions or follow-up questions.
      placeholder: What confuses me? Can the question be split/structured into multiple, separately answerable subquestions? Do I have follow-up questions?
    validations:
      required: true
  - type: textarea
    id: answer-contents
    attributes:
      label: Answer Contents
      description: Describe the information that the answer should provide as detailed as possible.
      placeholder: What information should the answer include to be satisfactory?
    validations:
      required: true  
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specify the acceptance criteria as a task list that contains one or more entries.
      placeholder: |
        - [ ] Do this
        - [ ] Do that
        ...
    validations:
      required: true
  - type: textarea
    id: further-information
    attributes:
      label: Further Information
      description: Add additional helpful, issue-related information, such as, links, screenshots, sketches, considerations, thoughts, etc.
      placeholder: Helpful information
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: Add a bullet point list of other related issues, in case there are any. In particular, the issue(s) (if you can narrow it/them down) that introduced the need for a <PLACEHOLDER> would be helpful.
      placeholder: |
        - #42
        - #73
        ...
