name: Bug Report
description: Something is not working (correctly)
title: "[Bug Report] kebap-cased-shortened-bug-behavior"
labels: ["Status: Pending", "Type: Bug Report"]
assignees:
  - L483
body:
  - type: markdown
    attributes:
      value: |
        Do **not** abuse a *bug report* to report *security vulnerabilities*.<br/>
        In such instances, act as described in the project's *security policy* or if the project does not specify how to report these incidents, open a *security advisory*.
        
        All text areas support markdown syntax unless explicitly noted otherwise.
  - type: input
    id: affected-version
    attributes:
      label: Affected Version
      description: Name the known versions or main branches of the project that the bug affects.
      placeholder: e.g. Project Version 1.2.1, Project Version 2.0.0
    validations:
      required: true
  - type: input
    id: system-information
    attributes:
      label: System Information
      description: Name any potentially helpful information about the system(s) where the bug appeared, like the operating system and its version, the browser and its version, device information, etc.
      placeholder: e.g. Windows 10 Pro 21H2 64-bit, Firefox 108.0.2 64-bit
    validations:
        required: true
  - type: textarea
    id: bug-behavior
    attributes:
      label: Bug Behavior
      description: Describe the bug's behavior as detailed as possible.
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe how you expected the program to behave as specifical as possible.
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Describe how to reproduce the bug step-by-step as detailed as possible. Use an ordered list for this.
      placeholder: |
        1. I started here.
        2. Then, I did this.
        ...
    validations:
      required: true
  - type: textarea
    id: solution-proposal
    attributes:
      label: Solution Proposal
      description: Describe the solution that you have in mind as detailed as possible, in case you know a fix.
      placeholder: How could the bug be solved?
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe potential side effects of your solution proposal, which could cause follow-up issues, to the best of your knowledge.
      placeholder: Could my solution proposal cause other problems?
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specify the acceptance criteria as a task list that contains one or more entries.
      placeholder: |
        - [ ] Do this
        - [ ] Do that
        ...
    validations:
      required: true
  - type: textarea
    id: further-information
    attributes:
      label: Further Information
      description: Add additional helpful, issue-related information, such as, links, screenshots, sketches, considerations, thoughts, etc.
      placeholder: Helpful information
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: Add a bullet point list of other related issues, in case there are any. In particular, the issue(s) (if you can narrow it/them down) that introduced the bug would be helpful.
      placeholder: |
        - #42
        - #73
        ...
  - type: markdown
    attributes:
      value: |
        **Information for contributors about label usage:**<br/>
        
        - select *any number* of fitting labels that have a `Flag: ` prefix
        - select *any number* of fitting labels that have a `For: ` prefix
        - select **exactly one** label that has a `Priority: ` prefix
        - select **exactly one** label that has a `Scope: ` prefix
        - **never** tamper with the initial `Status: Pending` label when creating an issue
        - **never** add, remove, or change any associations (or the lack thereof) between an issue and label that has a `Type: ` prefix
        
        Look at the label descriptions to grasp their proper usage and pick the most fitting.
        If more than one `Type: ` label fits the issue, it is a good indicator that the issue mixes concerns.
        You should then split this issue into multiple issues so that each new issue falls **exactly into one** category.
