name: Design
description: Refactor specifically concerning UI/UX improvements
title: "[Design] kebap-cased-issue-name"
labels: ["Status: Pending", "Type: Design"]
assignees:
  - L483
body:
  - type: markdown
    attributes:
      value: |
        If there are *multiple little improvement suggestions*, you can mention them bundled within a *single issue* because the effort of writing issues should not drastically surpass the effort of resolving them.<br/>
        Make sure to present each improvement **distinctly** from the rest and to use the **same order** of refinements in each section when bundling multiple improvements inside one issue.
        
        All text areas support markdown syntax unless explicitly noted otherwise.
  - type: textarea
    id: object-of-interest
    attributes:
      label: Object of Interest
      description: Describe the UI/UX parts that require design overwork as specifical as possible.
      placeholder: What does look wrong/disruptive/outdated?
    validations:
      required: true
  - type: textarea
    id: problem-motivation
    attributes:
      label: Problem/Motivation
      description: Describe your problem or motivation that caused your design request as detailed as possible.
      placeholder: Why does it seem wrong/disruptive/outdated?
    validations:
      required: true
  - type: textarea
    id: solution-proposal
    attributes:
      label: Solution Proposal
      description: Describe the solution that you have in mind as detailed as possible.
      placeholder: How should it be designed to look correct/consistent/modern?
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe potential side effects of your solution proposal, which could cause follow-up issues (in particular design requests), and explain how/whether the corresponding functionality behind the design changes could be affected, to the best of your knowledge.
      placeholder: Could my solution proposal cause other problems?
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specify the acceptance criteria as a task list that contains one or more entries.
      placeholder: |
        - [ ] Do this
        - [ ] Do that
        ...
    validations:
      required: true
  - type: textarea
    id: further-information
    attributes:
      label: Further Information
      description: Add additional helpful, issue-related information, such as, links, screenshots, sketches, considerations, thoughts, etc.
      placeholder: Helpful information
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: Add a bullet point list of other related issues, in case there are any. In particular, the issue(s) (if you can narrow it/them down) that introduced the need for a design change would be helpful.
      placeholder: |
        - #42
        - #73
        ...
  - type: markdown
    attributes:
      value: |
        **Information for contributors about label usage:**<br/>
        
        - select *any number* of fitting labels that have a `Flag: ` prefix
        - select *any number* of fitting labels that have a `For: ` prefix
        - select **exactly one** label that has a `Priority: ` prefix
        - select **exactly one** label that has a `Scope: ` prefix
        - **never** tamper with the initial `Status: Pending` label when creating an issue
        - **never** add, remove, or change any associations (or the lack thereof) between an issue and label that has a `Type: ` prefix
        
        Look at the label descriptions to grasp their proper usage and pick the most fitting.
        If more than one `Type: ` label fits this issue, it is a good indicator that the issue mixes concerns.
        You should then split this issue into multiple issues so that each new issue falls **exactly into one** category.
