name: Question
description: Something needs clarification or further information and may uncover problems
title: "[Question] kebap-cased-shortened-question"
labels: ["Status: Pending", "Type: Question"]
assignees:
  - L483
body:
  - type: markdown
    attributes:
      value: |
        All text areas support markdown syntax unless explicitly noted otherwise.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Write your question in full length as detailed as possible. Describe the object of confusion as specifical as possible. Also, describe possible subquestions or follow-up questions.
      placeholder: What confuses me? Can the question be split/structured into multiple, separately answerable subquestions? Do I have follow-up questions?
    validations:
      required: true
  - type: textarea
    id: answer-contents
    attributes:
      label: Answer Contents
      description: Describe the information that the answer should provide as detailed as possible.
      placeholder: What information should the answer include to be satisfactory?
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specify the acceptance criteria as a task list that contains one or more entries, for example, by splitting the question into different, separately answerable parts.
      placeholder: |
        - [ ] Do this
        - [ ] Do that
        ...
    validations:
      required: true
  - type: textarea
    id: further-information
    attributes:
      label: Further Information
      description: Add additional helpful, issue-related information, such as, links, screenshots, sketches, considerations, thoughts, etc.
      placeholder: Helpful information
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: Add a bullet point list of other related issues, in case there are any. In particular, the issue(s) (if you can narrow it/them down) that caused your confusion would be helpful.
      placeholder: |
        - #42
        - #73
        ...
  - type: markdown
    attributes:
      value: |
        **Information for contributors about label usage:**<br/>
        
        - select *any number* of fitting labels that have a `Flag: ` prefix
        - select *any number* of fitting labels that have a `For: ` prefix
        - select **exactly one** label that has a `Priority: ` prefix
        - select **exactly one** label that has a `Scope: ` prefix
        - **never** tamper with the initial `Status: Pending` label when creating an issue
        - **never** add, remove, or change any associations (or the lack thereof) between an issue and label that has a `Type: ` prefix
        
        Look at the label descriptions to grasp their proper usage and pick the most fitting.
        If more than one `Type: ` label fits this issue, it is a good indicator that the issue mixes concerns.
        You should then split this issue into multiple issues so that each new issue falls **exactly into one** category.
