name: Testing
description: Improvements to the test suite, as well as pointing out wrong or missing tests
title: "[Testing] kebap-cased-issue-name"
labels: ["Status: Pending", "Type: Testing"]
assignees:
  - L483
body:
  - type: markdown
    attributes:
      value: |
        Do **not abuse** a *testing* issue to test out new stuff that may or may not be included in the project, like, experimenting with new tools to see whether you can get them to work or whether they are appropriate for the project.
        Use a *feature request* or a *feature change request* instead, work on them on their own branch, and (if fitting) mark them with the `Flag: Suggestion` label.
        Keep in mind not all *opened* and *accepted* issues have to be resolved. They can also be *abandoned* if the experiments turn out as a fail.
        
        If there are *multiple little improvement suggestions*, you can mention them bundled within a *single issue* because the effort of writing issues should not drastically surpass the effort of resolving them.<br/>
        Make sure to present each improvement **distinctly** from the rest and to use the **same order** of refinements in each section when bundling multiple improvements inside one issue.
        However, create a **separate** issue for each issue that is concerned with the *test suite* itself.
        
        All text areas support markdown syntax unless explicitly noted otherwise.
  - type: textarea
    id: object-of-interest
    attributes:
      label: Object of Interest
      description: Describe the test suite parts/ the tests that require overwork as specifical as possible.
      placeholder: Where are tests wrong/incomplete/missing? Where could the test suite be improved?
    validations:
      required: true
  - type: textarea
    id: problem-motivation
    attributes:
      label: Problem/Motivation
      description: Describe your problem or motivation that caused your testing request as detailed as possible.
      placeholder:  Why do tests seem wrong/incomplete/missing? Why does the test suite need an improvement?
    validations:
      required: true
  - type: textarea
    id: solution-proposal
    attributes:
      label: Solution Proposal
      description: Describe the solution that you have in mind as detailed as possible.
      placeholder: How would you write the tests? How could the test suite be improved?
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe potential side effects of your solution proposal, which could cause follow-up issues (usually only relevant when suggesting changes to the test suite), to the best of your knowledge.
      placeholder: Could my solution proposal cause other problems?
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Specify the acceptance criteria as a task list that contains one or more entries.
      placeholder: |
        - [ ] Do this
        - [ ] Do that
        ...
    validations:
      required: true
  - type: textarea
    id: further-information
    attributes:
      label: Further Information
      description: Add additional helpful, issue-related information such as links, screenshots, sketches, considerations, thoughts, etc.
      placeholder: Helpful information
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: Add a bullet point list of other related issues, in case there are any. In particular, the issue(s) (if you can narrow it/them down) that introduced the need for a testing request would be helpful.
      placeholder: |
        - #42
        - #73
        ...
  - type: markdown
    attributes:
      value: |
        **Information for contributors about label usage:**<br/>
        
        - select *any number* of fitting labels that have a `Flag: ` prefix
        - select *any number* of fitting labels that have a `For: ` prefix
        - select **exactly one** label that has a `Priority: ` prefix
        - select **exactly one** label that has a `Scope: ` prefix
        - **never** tamper with the initial `Status: Pending` label when creating an issue
        - **never** add, remove, or change any associations (or the lack thereof) between an issue and label that has a `Type: ` prefix
        
        Look at the label descriptions to grasp their proper usage and pick the most fitting.
        If more than one `Type: ` label fits this issue, it is a good indicator that the issue mixes concerns.
        You should then split this issue into multiple issues so that each new issue falls **exactly into one** category.
